# Generated by Django 5.0.2 on 2025-03-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Software Development', 'Software Development'), ('Human Resources (HR)', 'Human Resources (HR)'), ('Marketing & Advertising', 'Marketing & Advertising'), ('Sales & Business Development', 'Sales & Business Development'), ('Customer Support', 'Customer Support'), ('Creative & Design', 'Creative & Design')], max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('total_experience', models.CharField(max_length=50)),
                ('key_skills', models.TextField()),
                ('degree', models.CharField(max_length=255)),
                ('additional_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.jobapplication')),
            ],
        ),
    ]
