# Generated by Django 5.1.5 on 2025-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
