# Generated by Django 5.1.5 on 2025-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_jobapplication_name_selectedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
