# Generated by Django 5.1.5 on 2025-04-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jobapplication_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_selected',
        ),
        migrations.DeleteModel(
            name='SelectedCandidate',
        ),
    ]
