# Generated by Django 5.1.5 on 2025-04-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_jobapplication_is_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.extractdetails')),
            ],
        ),
    ]
