# Generated by Django 5.1.5 on 2025-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_selectedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractdetails',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
